# Generated by Django 5.2.5 on 2025-08-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('d', 'done'), ('p', 'pending'), ('t', 'terminated')], default='p', max_length=1),
        ),
    ]
