# Generated by Django 5.2.5 on 2025-08-28 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_todo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='disc',
        ),
    ]
